language: python

matrix:
  include:
    - os: osx
      osx_image: xcode8
      language: generic
      env:
        - TOXENV=py27
    - os: osx
      osx_image: xcode8
      language: generic
      env:
        - TOXENV=py36
    - os: linux
      python: 2.7
      env:
        - TOXENV=py27
    - os: linux
      python: 3.6
      env:
        - TOXENV=py36

before_install:
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

script:
  - ./.travis/test.sh
